### ISSUE TITLE
Create Tadukoo Engine (Alpha v.0.1)

### ISSUE THREAD

**Issue by Tadukoo** [Tadukoo/TadukooUtil#1]
Create a new module called Tadukoo Engine that combines everything into one consistent Engine ViewBase, Engine Context, etc. for actual programs to just extend Tadukoo Engine's stuff to use in creating the basics of the program.

<b>Note: This item is worded as if it has been here from the beginning, just to be a full list of everything in working towards it</b>

Tadukoo Engine essentially requires everything else to exist in addition to its own work.

- [ ] Create Tadukoo Util
  - [x] Create StringBuilderUtil (#7)
- [ ] Create Tadukoo File Format
- [ ] Create Tadukoo Database
- [ ] Create Tadukoo View
  - [x] Make Text color no longer hard-coded (#6)
  - [ ] Make Button size more flexible (#11)
  - [ ] Finish Text Input (#5)
  - [ ] Create Forms (#4)
- [ ] Create Tadukoo Accounts (#2)
- [ ] Create Tadukoo Engine (this)

**Comment by Tadukoo** [comment]
Cancelling this issue, as it was written under the ideas of old plans
